# Generated by Django 3.1.7 on 2021-03-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('product_brand', models.CharField(max_length=100, verbose_name='Product Brand')),
                ('product_quantity', models.IntegerField(verbose_name='Quantity')),
                ('product_price', models.IntegerField(verbose_name='Price')),
                ('product_mfd', models.DateField(verbose_name='Manufacturing Date')),
                ('product_exp', models.DateField(verbose_name='Expiry Date')),
            ],
        ),
    ]
