# Generated by Django 3.1.7 on 2021-03-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_barcode',
            field=models.IntegerField(null=True, unique=True, verbose_name='Barcode Number'),
        ),
    ]
