# Generated by Django 3.1.7 on 2021-03-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_auto_20210322_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_barcode',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Barcode Number'),
        ),
    ]
