# Generated by Django 3.1.7 on 2021-03-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_auto_20210322_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_barcode',
            field=models.IntegerField(null=True, unique=True, verbose_name='Barcode Number'),
        ),
    ]
