# Generated by Django 3.1.7 on 2021-03-18 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_amount', models.IntegerField(verbose_name='Amount')),
                ('bill_date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('bil_quantity', models.IntegerField(verbose_name='Quantity')),
                ('bill_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer', verbose_name='Bought By')),
                ('bill_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='Product')),
            ],
        ),
    ]
