# Generated by Django 3.1.7 on 2021-03-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
