# Generated by Django 3.1.7 on 2021-03-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0002_bill_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='bil_quantity',
            new_name='bill_quantity',
        ),
    ]
