# Generated by Django 3.1.7 on 2021-03-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0004_auto_20210320_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
