# Generated by Django 3.1.7 on 2021-03-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0005_auto_20210320_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='slug',
        ),
    ]
