# Generated by Django 3.1.7 on 2021-03-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0007_auto_20210321_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solditem',
            old_name='bill_quantity',
            new_name='quantity',
        ),
    ]
