# Generated by Django 3.1.7 on 2021-03-22 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_auto_20210320_1328'),
        ('Bill', '0008_auto_20210321_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solditem',
            name='customer',
        ),
        migrations.AddField(
            model_name='bill',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.customer', verbose_name='Bought By'),
        ),
    ]
