# Generated by Django 3.1.7 on 2021-03-22 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0009_auto_20210322_1039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporatyStorage',
        ),
    ]
