# Generated by Django 3.1.7 on 2021-03-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0010_delete_temporatystorage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solditem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='solditem',
            name='individual_price',
            field=models.FloatField(default=0, verbose_name='Amount'),
            preserve_default=False,
        ),
    ]
