# Generated by Django 3.1.7 on 2021-03-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0011_auto_20210322_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='solditem',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
            preserve_default=False,
        ),
    ]
